# Generated by Django 3.1.7 on 2021-02-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210225_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codeMelli',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reffrall',
            field=models.CharField(default='ue3vkobe4j', editable=False, max_length=10, unique=True, verbose_name='کد بازاریابی'),
        ),
    ]
