# Generated by Django 3.1.7 on 2021-02-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210225_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codeMelli',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reffrall',
            field=models.CharField(default='jun4wsoygk', editable=False, max_length=10, unique=True, verbose_name='کد بازاریابی'),
        ),
    ]
