# Generated by Django 3.1.7 on 2021-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('n', 'جدید'), ('p', 'انتشار یافته'), ('i', 'در حال بررسی'), ('b', 'بسته')], max_length=5),
        ),
    ]
