# Generated by Django 3.1.7 on 2021-02-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('n', 'جدید'), ('i', 'در حال بررسی'), ('p', 'انتشار یافته'), ('b', 'بایگانی')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
