# Generated by Django 3.1.7 on 2021-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertify', '0003_auto_20210222_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codeMelli',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reffrall',
            field=models.CharField(default='hj2ugebci0', editable=False, max_length=10, unique=True),
        ),
    ]
