# Generated by Django 3.1.7 on 2021-02-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertify', '0004_auto_20210222_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reffrall',
            field=models.CharField(default='oxbw0tv2sx', editable=False, max_length=10, unique=True),
        ),
    ]
