# Generated by Django 3.1.7 on 2021-02-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vertify', '0006_auto_20210224_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activeAcc',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='codeMelli',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reffrall',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telphone',
        ),
    ]
