# Generated by Django 3.1.7 on 2021-02-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vertify', '0007_auto_20210225_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
    ]
